[phases.setup]
aptPkgs = [
    'chromium',
    'chromium-sandbox',
    'nss',
    'freetype',
    'harfbuzz',
    'ca-certificates',
    'fonts-liberation',
    'libappindicator3-1',
    'libasound2',
    'libatk-bridge2.0-0',
    'libatk1.0-0',
    'libcups2',
    'libdbus-1-3',
    'libdrm2',
    'libgbm1',
    'libgtk-3-0',
    'libnspr4',
    'libnss3',
    'libx11-xcb1',
    'libxcomposite1',
    'libxdamage1',
    'libxrandr2',
    'xdg-utils',
    'libglib2.0-0'
]

[start]
cmd = "node bot.js"
